USE [EPA_PubNumbers]
GO

INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(100, 'Administrator/Deputy Administrator and publications Printed before 1992')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(110, 'Administrative Law Judges')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(160, 'Assistant administrator for international affairs')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(454, 'Air Quality Assessment Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(457, 'Air quality Policy Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(452, 'Health and Environmental Impacts Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(400, 'Immediate Office')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(450, 'Office of Air Quality Planning and Standards (OAQPS)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(430, 'Office of Atmospheric Programs (OAP)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(420, 'Office of Mobile Sources (OMS)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(410, 'Office of Policy Analysis and Review (OPAR)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(440, 'Office of Program Management Operations')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(402, 'Office of Radiation Programs and Indoor Air (ORPIA)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(451, 'office of the director/intermedia programs')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(456, 'Outreach and Information Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(453, 'Sector Policies and Programs')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(455, 'Stationary Source Compliance Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(739, 'Antimicrobial Division (AD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(733, 'Biological and Economical Analysis Division (BEAD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(731, 'Bio pesticides and Pollution Prevention Division (BPPD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(703, 'Bio Technology Staff')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(743, 'Chemical Control Division (COD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(746, 'Chemical Screening and Risk Assessment Division (CSRAD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(722, 'Compliance Division (CD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(721, 'Directors Office')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(741, 'Directors Office and Office of Program Management and Evaluation (OPME)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(744, 'Economics Exposure and Technology Division (EETD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(745, 'Environmental Assistance Division (EAD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(734, 'Environmental Fate and Effect Division (EFED)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(712, 'Federal Register Staff')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(735, 'Field and External Affairs Division (FEAD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(748, 'Health and Environmental Review Division (HERD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(736, 'Health Effects Division (HED)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(749, 'Information Management Division (IMD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(732, 'Information Resources and Services Division (IRSD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(723, 'Laboratory Data Integrity Assurance Division (LDIAD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(747, 'National Program Chemical Division (NPCD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(720, 'Office of Compliance Monitoring (OCM)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(730, 'Office of Pesticide Programs and Directors Office (OPP)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(740, 'Office of Pollution Prevention and ToxIcs (OPPT)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(710, 'Office of Program Management Operations')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(701, 'Office of Science Coordination and Policy')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(700, 'Office of the Assistant Administrator (OAA)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(724, 'Policy and Grants Division (PGD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(742, 'Pollution Prevention Division (CCD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(737, 'Registration Division (RD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(702, 'Regulatory Coordination Staff')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(711, 'Resource Management Staff')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(230, 'Immediate Office (OI)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(236, 'Office of Economy and Environment (OEE)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(231, 'Office of Policy Development (OPD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(232, 'Office of Programmatic Support and Resources Management (OPSRM)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(233, 'Office of Regulatory Management and Information (ORMI)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(234, 'Office of Strategic Planning and Environmental Data (OSPED)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(237, 'Office of Sustainable Ecosystems and Communities (OSEC)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(601, 'Assistant Administrator for Research and Development (ORD/CERI)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(620, 'Assistant Administrator for Research and Development (ORD/CERI)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(665, 'National Center for Environmental Assessment (NCEA)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(655, 'National Center for Environmental Research and Quality Assurance (NCR)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(615, 'National Exposure Research Laboratory (NERL)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(645, 'National Health and Environmental Effects Research Laboratory (NHEERL)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(600, 'National Risk Management Research Laboratory (NRMRL)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(625, 'National Risk Management Research Laboratory (NRMRL)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(602, 'Office of Aging (OA)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(675, 'Office of Science Policy (OSP)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(550, 'Chemical Emergency Preparedness and Prevention Office (CEPPO)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(505, 'Federal Facilities Restoration and Reuse Office (FFRRO)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(500, 'Immediate Office, OMIS, RMIS, PARMS')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(545, 'National Response Team (NRT)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(540, 'Office of Emergency and Remedial Response (Superfund), OPM, ERD, HSCD')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(530, 'Office of Solid Waste (OSW) MOWD, CABD, WMD, PSPD, CAD')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(510, 'Office of Underground Storage Tanks (OUST), PSD, Implementation Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(520, 'Office of Waste Programs Enforcement (OWPE,), CERCLA Enforcement, RCRA Enforcement')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(541, 'Record of Decision (ROD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(542, 'Technology Innovation Office (TIO)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(851, 'American Indian Environmental Office (OW-AIEO)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(841, 'Assessment and Watershed Protection Division (AWPD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(831, 'Enforcement Division (ED)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(821, 'Engineering and Analysis Division (EAD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(855, 'Glf of Mexico Program (GMP)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(822, 'Health and Ecological Criteria Division (HECD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(816, 'IAD, RIB, PSB, IMB')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(800, 'Immediate Office (OW)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(832, 'Municipal Support Division (MSD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(842, 'Oceans and Coastal Protection Division (OCPD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(810, 'Office of Ground Water and Drinking Water (OGWDW)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(820, 'Office of Science and Technology (OST)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(830, 'Office of Wastewater Management (OWM)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(840, 'Office of Wetlands, Oceans and Watersheds (OSOS)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(833, 'Permits Division (PD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(850, 'Policy and Resources Management Office')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(815, 'SRMD, TAB, SRRB, TSCB')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(823, 'Standards and Applied Science Division (SASD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(817, 'Water Security Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(843, 'Wetlands Division (WD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(205, 'Office of the Comptroller (OC)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(218, 'Office of Acquisition Management (OAM)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(212, 'Office of Administration �Cincinnati')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(208, 'Office of Administration-RTP (OA-RTP)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(202, 'Office Administration-Washington')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(216, 'Office of Grants and Debarment')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(210, 'Office of Human Resources and Organizational Services (OHROS)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(219, 'Office of Information and Resource Management (OIRM)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(200, 'Office of the Assistant Administrator (OA)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(220, 'Office of the Assistant Administrator (OA)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(201, 'Program and Policy Coordination Office')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(172, 'Communications Planning Division (CPD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(175, 'Editorial Services Division (ESD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(171, 'Environmental Education')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(174, 'External Relations Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(170, 'Immediate Office and Special Projects')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(176, 'Media Relations Division (MD)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(173, 'Press Division')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(270, 'Associate Administrator for Regional Operations and State/Local Relation (AAROSLR)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(560, 'Brownfields')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(190, 'Chief Financial Office (CFO)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(155, 'Children Health Protection')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(150, 'Civil Rights')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(130, 'Cooperative Environment Management (OCEM)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(360, 'General Counsel (OGC)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(350, 'Inspector General (OIG)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(930, 'Central Regional Laboratory, Annapolis MD')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(900, 'Joint Print W/Outside Agency')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(901, 'Region 1')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(910, 'Region 10')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(902, 'Region 2')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(903, 'Region 3')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(904, 'Region 4')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(905, 'Region 5')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(906, 'Region 6')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(907, 'Region 7')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(908, 'Region 8')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(909, 'Region 9')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(950, 'US EPA Published')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(300, 'Assistant Administrator for Enforcement and Compliance Assurance (OECA)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(331, 'National Enforcement Investigations Center')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(305, 'Office of Compliance (OC)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(310, 'Office of Criminal Enforcement')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(315, 'Office of Federal Activities (OFA)')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(325, 'Office of Regulatory Enforcement')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(330, 'Office of Site Remediation')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(240, 'Immediate Office')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(260, 'Office of Information Analysis and Access')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(250, 'Office of Information Collection')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(255, 'Office of Information Technology Services')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(245, 'Office of Planning, Resources and Outreach')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(120, 'Science Advisory Board')
INSERT INTO [dbo].[ResponsibleCodes]([Code],[Organization])VALUES(180, 'Small and Disadvantaged Business Utilization')
GO


